### ISSUE TITLE
Slide off Platform

### ISSUE THREAD

**Issue by rachelgroth** [gadsu/cleanup#13]
**Describe the bug**
Sliding off a platform allows you to move in midair

**To Reproduce**
1.Slide off a platform without jumping
2. Jump
3. Be able to jump

**Expected behavior**
Sliding off a ledge should prevent you from being able to jump

**Comment by rex8112** [comment]
Fixed in commit 208ab082c00a5df6131c3cefdae07ac1b4b9f08d

**Comment by rex8112** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0.5) Fix player jumping after walking off a platform [0.5]](https://trello.com/c/X6mh5lVT/259-05-fix-player-jumping-after-walking-off-a-platform-05)
