### ISSUE TITLE
Can't Jump If on Slime

### ISSUE THREAD

**Issue by rex8112** [gadsu/cleanup#26]
**Describe the bug**
If the player jumps while on place slime and lands on the slime, they are unable to jump again without leaving the slime. This was discovered by the slime that emerges from killing a goopa

**To Reproduce**
1. Place floor slime or kill Goopa.
2. Jump on slime and land on slime
3. Be unable to jump again

**Expected behavior**
Slime should count as the floor

**Additional Information**
Due to #25 if, at any point in your jump, the slime is not beneath you, it will allow you to jump once more.

**Comment by IanTrollinger** [comment]
Seems like this also applies to the slime balls, the kind that do not drop from enemy slimes, if you land on them you cannot jump. However I've noticed that if you walk off them onto the ground art assets you can jump again. However for the ground without an art asset it doesn't allow jumping again. (Level 1) This is only the case if you ended the jump on slime, if you go back on dirt or fall off a ledge and land on any ground, you can jump.

**Comment by rex8112** [comment]
This was fixed in 64724887de2bceb8d9b1aafc48c7ce3a3033ac64
