### ISSUE TITLE
Cleaning slime on Keyboard

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#32]
**Describe the bug**
When using the keyboard instead of the controller. The 'E' key we chose of cleaning the ground doesn't seem to clean the ground underneath. 

**To Reproduce**
1. Kill slime
2. Press E while over the dropped slime
3. Cannot pick up slime

**Expected behavior**
Expected to clean up slime on ground and raise the slime held.

**Screenshots**

**Additional context**
I was going to do a test to see if having max green slime keeps the player from cleaning up extra slime.

**Comment by rex8112** [comment]
Did you... By chance... Start the game on _DontDestroyOnLoad or on greenLevel? Was it built or not? Was it the updated master branch or the outdated Narrative Branch?

**Comment by ladyflyers29** [comment]
Tested on the latest master branch while starting on _DontDestroyOnLoad as intended. Works perfectly.
