### ISSUE TITLE
Player animations weird

### ISSUE THREAD

**Issue by cjpetersen** [gadsu/cleanup#34]
**Branch or release bug is on**
 v0.6.2-alpha on the programming branch as of commit 0475fa
**If found on Unity editor, what scene did you load**
Testing Scene

**Describe the bug**
The Sprites for the player animations Idle, Run and Jump switch direction in addition to what side the mop is on and this is making it impossible to get the run animation to sync to the jump animation. 
**To Reproduce**
1. Go to 'Testing cene'
2. Click on 'Play'
3. Run around and jump

**Expected behavior**
I should jump and still be facing the direction I was running

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add player animations to unity (2)[2.75]](https://trello.com/c/6gg3fxT0/245-add-player-animations-to-unity-2275)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add player animations to unity (2)[2.75]](https://trello.com/c/6gg3fxT0/245-add-player-animations-to-unity-2275)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add player animations to unity (2)[2.75]](https://trello.com/c/6gg3fxT0/245-add-player-animations-to-unity-2275)

**Comment by ladyflyers29** [comment]
![animationglitch](https://user-images.githubusercontent.com/42610874/49029671-c80e2e00-f16a-11e8-908f-66323cf6a98a.gif)

**Comment by cjpetersen** [comment]
I thought I fixed that walking backward thing I know how to fix it with code but its kinda jank.

**Comment by rex8112** [comment]
Nick flipped the sprites and its better now but not all the way fixed also this 
![image](https://user-images.githubusercontent.com/6889658/49119681-d7769f80-f26e-11e8-800a-a80e85f1f397.png)

-Carl

**Comment by cjpetersen** [comment]
Changed the landing animation transition and fixed code to accommodate it, still some jankyness. 
The bug was merged into Master v0.6.3-alpha as it doesn't break the game it will continue in the game until fixed.

**Comment by rex8112** [comment]
More detail, sprite seems to flip when facing right and jumping
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6889658/49400192-1b532400-f709-11e8-983a-7f7d196c0adf.gif)

**Comment by cjpetersen** [comment]
Fixed, added new code to control player animations in playerController script.
