### ISSUE TITLE
Tilemap Errors

### ISSUE THREAD

**Issue by rex8112** [gadsu/cleanup#38]
**Branch or release bug is on**
MiffedKomodoDragon v0.7.0-alpha

**Describe the bug**
Tilemap errors on tutorialLevel

**Screenshots**
![image](https://user-images.githubusercontent.com/6889658/49400271-5bb2a200-f709-11e8-8d42-46ce2c3ef231.png)

**Comment by rachelgroth** [comment]
fixed a while ago and never closed
