### ISSUE TITLE
Rotation bug, rb.constraints

### ISSUE THREAD

**Issue by cjpetersen** [gadsu/cleanup#39]
**Branch or release bug is on**
Tell us what version you're running to better find the bug.
 v0.7.0-alpha 

**If found on Unity editor, what scene did you load**
_DontDestroyOnLoad

**Describe the bug**
When you jump onto a green slime wall you rotation is unfrozen and if you land on a corner while rotation is unfrozen you rotate and can not get back to your normal upright position.

**To Reproduce**
1. Go to the green level and jump on a green slime wall. 
2. See error

**Expected behavior**
Stay upright
**Screenshots**
![image](https://user-images.githubusercontent.com/25103835/51338594-d896a280-1a4f-11e9-9521-16c880fbf1d6.png)

Video
[RotationBugJan17.zip](https://github.com/gadsu/cleanup/files/2769974/RotationBugJan17.zip)

**Additional context**

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the rotation bug (.5)](https://trello.com/c/G8IfjTJJ/306-fix-the-rotation-bug-5)

**Comment by ladyflyers29** [comment]
FIxed. The Position was being frozen and not both the position and the rotation.
