### ISSUE TITLE
Menu Buttons Broken

### ISSUE THREAD

**Issue by ladyflyers29** [gadsu/cleanup#43]
**Branch or release bug is on**
Tell us what version you're running to better find the bug.
 on v0.8.0-alpha - Oppressed Opossum Commit 024b629 
**If found on Unity editor, what scene did you load**
For example: "Tutorial Level", "Green Level", "Testing Level"
**Describe the bug**
Resume, Quit, etc do nothing
**To Reproduce**
1. Go to 'Don't Destroy on Load'
2. Click on 'Start'
3. Press the 'escape key'
2. Click on 'Resume'

**Expected behavior**
The game should resume

**Comment by ladyflyers29** [comment]
Works in Unity 2.5f doesn't work in 3.1.

**Comment by rachelgroth** [comment]
did this get fixed?

**Comment by ladyflyers29** [comment]
I believe so

-Brooke



On Mon, Jan 28, 2019 at 3:41 PM -0600, "rachelgroth" <notifications@github.com<mailto:notifications@github.com>> wrote:


did this get fixed?
