### ISSUE TITLE
Wall jump can be broken

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#46]
Current Master Branch build

Used "Don't destroy on load" and used save slot to to go to level 2.

Can break the ability to wall jump. You can latch to the wall but cannot jump off the wall.

I was testing a possible bug where if the player is stuck to the wall with a slime overhead the player is stuck in place. Slime fell on player when jumping off and caused damage. Was unable to wall jump after that. Several other possible things could have caused it, such as the bug I was testing (Proved to be fixable by just stopping movement)

Was unable to get past beginning of the first level as was unable to jump to the top of the platform.

**Screenshots**

**Additional context**

**Comment by rex8112** [comment]
Could be something connected with the knockback function, I'll look into here in 20 minutes.

**Comment by cjpetersen** [comment]
@rex8112 did you ever reproduce this or figure out what it was?

**Comment by ladyflyers29** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Fix issue #46](https://trello.com/c/he5fmFbN/339-1-fix-issue-46)

**Comment by cjpetersen** [comment]
And take a video with obs or something or remind me when we share a work block and ill watch how you get the bug.

**Comment by rex8112** [comment]
Although some inconvenience can occur from this, it is no longer permanent as of be19c79ac42dbe5eda13df1643ed871882363a64
