### ISSUE TITLE
Health and slime not updating upon scene change.

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#47]
Found on Programming branch.

Loaded Don't destroy on load.

Went through the tutorial level and completed it with low health and high slime. Upon starting the Green level the game said I had full health and no slime. I was still able to wall jump without slime and died from one hit from a slime.

See above to reproduce.

I expected I'd have to collect some slime to wall jump and had full health. I did not.

**Screenshots**

Something might not be updating during the scene transition.

**Comment by cjpetersen** [comment]
Present after v0.8.0-alpha OppressedOpossum Commit aeb0599, It is intended to reset health and Slime when you start a new level - Dillon

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(.5)[.5]](https://trello.com/c/hMyjpFXT/334-55)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(.5)[.5]](https://trello.com/c/hMyjpFXT/334-55)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(.5)[.5]](https://trello.com/c/hMyjpFXT/334-55)
