### ISSUE TITLE
OBSOO Ground Slam removes player control momentarily

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#48]
Done on Programming

Loaded Don't destroy on load, Started on the first level, tested out OBSOOO

OBSOOO, after hitting you with his ground slam can crash the game when he kills you after it.

1. Enter OBSOOO areana.
2. Let OBSOOO hit you with the ground slam.
3. Your character will walk in the direction he was facing and won't stop. No player input can fix it.
4. When OBSOOO kills you the game will freeze and crash.

Wanted to test out obsooo and death screen. This bad bug rendered me unable to test the death screen but gave a clear problem with OBSOOO's jump.

**Screenshots**

**Additional context**

**Comment by cjpetersen** [comment]
Found after v8.0 alpha OppressedOposum on the programming branch commit aeb0599 can be reproduced on don't destroy on load.

**Comment by rachelgroth** [comment]
please retest and confirm if this is still the case

**Comment by cjpetersen** [comment]
Cannot replicate as of commit 47e47b1
