### ISSUE TITLE
OBSOOO Ignores player collider after slam

### ISSUE THREAD

**Issue by cjpetersen** [gadsu/cleanup#50]
**Branch or release bug is on**
Tell us what version you're running to better find the bug.

Found after v8.0 alpha OppressedOposum on the programming branch commit aeb0599 

**If found on Unity editor, what scene did you load**
_DontDestroyOnLoad

**Describe the bug**
When OBSOOO does his down slam he sometimes phases through the player collider and then acts like the player doesn't exist. After this point, he does no dmg too and does not collide with the player.

**To Reproduce**
1. Go to **_DontDestroyOnLoad**
2. Click on **Play**
3. Enter Obscoos area and wait for the slam, let it hit you. 

**Expected behavior**
OBSOOO should deal damage to you

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(.5)[.5] Tested the Tutorial Level and created bug reports #49 and #50](https://trello.com/c/tAVYxuyc/335-55-tested-the-tutorial-level-and-created-bug-reports-49-and-50)

**Comment by shadowweaver95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug](https://trello.com/c/PKZjZTKx/353-fix-bug)

**Comment by shadowweaver95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug](https://trello.com/c/PKZjZTKx/353-fix-bug)

**Comment by IanTrollinger** [comment]
[OBSOOO WALL BREAK.zip](https://github.com/gadsu/cleanup/files/2836938/OBSOOO.WALL.BREAK.zip)

**Comment by rex8112** [comment]
Might want to test this again, we removed a potential culprit but I'm not sure if it fixed this issue

**Comment by cjpetersen** [comment]
Tested cannot replicate as of commit 47e47b1
