### ISSUE TITLE
Friendly Slimes

### ISSUE THREAD

**Issue by Free-Shaman** [gadsu/cleanup#54]
**Branch or release bug is on**
Programming, Release was something penguin, date found 2-5-19

**If found on Unity editor, what scene did you load**
`_DontDestroyOnLoad`

**Describe the bug**
If you get hit by one of the two starting slimes, there seems to be a short window where you can walk into them and they wont hurt you.

**To Reproduce**
1. Go to the first two slimes in the tutorial level
2. Get hit by one so that you land right next to the other without getting hit by the second
3. Walk into the one you landed next to as soon as you land, this seems to allow you to walk into the slime
4. Have fun with your couple of slime friends
(this is how it happened to me, not sure how easy it is to get to happen again as i havent been able to replicate it every time)

![slime buddies](https://user-images.githubusercontent.com/42610864/52301126-464b3580-294f-11e9-924d-a2274b94e355.png)

**Comment by shadowweaver95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug](https://trello.com/c/PKZjZTKx/353-fix-bug)

**Comment by ladyflyers29** [comment]
refer to #50
