### ISSUE TITLE
Breakable Jump in Scene transition

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#55]
**Branch or release bug is on**
b42070b

**If found on Unity editor, what scene did you load**
Loaded from Don'tDestroy and it's the transition from the Tutorial to Green Level

**Describe the bug**
Player will be unable to jump at all in the Green Level.

**To Reproduce**
1. At the end of the first level, if the player is in the air and interact with the exit they will be unable to jump in the next scene.

**Expected behavior**
Expected nothing to happen, and the game to function normally

[Transition Jump Break.zip](https://github.com/gadsu/cleanup/files/2837157/Transition.Jump.Break.zip)

**Comment by rex8112** [comment]
This is because the tilemaps are on the default layer when they need to be on the platform tilemap, should be fixed once the levels start being remade.

**Comment by rachelgroth** [comment]
seems to have been resolved
