### ISSUE TITLE
falling animation fix

### ISSUE THREAD

**Issue by shadowweaver95** [gadsu/cleanup#56]
**Programming**
3.1.f1.

`_DontDestroyOnLoad`

Falling Animation Mop has only one frame.

1. Go to '_DontDestroyOnLoad'
2. Press Play
3. Jump.

More frames are expected.

**Comment by rachelgroth** [comment]
added the missing frames to the animation

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bugs 56, 58, 60 (1.5)](https://trello.com/c/G2Liw5Ny/376-fix-bugs-56-58-60-15)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bugs 56, 58, 60 (1.5)](https://trello.com/c/G2Liw5Ny/376-fix-bugs-56-58-60-15)
