### ISSUE TITLE
The Slimes are invisible

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#57]
**Branch or release bug is on**
b42070b

**If found on Unity editor, what scene did you load**
Don't Destroy on Load

**Describe the bug**
There seems to be on tutorial level, they cannot be seen and can cause damage. They also seem to spawn rapidly

**To Reproduce**
1. Launch Don'tdestroyonload
2. Press start.
3. Experience invisible enemies.
**Expected behavior**
Expected to see slimes at the very least or see if the updates broke the game.
**Screenshots**

**Additional context**
I'm not sure if someone messed with some code they shouldn't have messed with, but you can't play the levels now and I can't test to see if there are any new bugs or if some were fixed.

**Comment by IanTrollinger** [comment]
Messed up the program version, correct version is  1cfcb58, used Narrative version instead of Programming. I am testing on the correct branch though.

**Comment by rachelgroth** [comment]
Riley fixed this and carl broke it
