### ISSUE TITLE
restarting the level does not reset values

### ISSUE THREAD

**Issue by rachelgroth** [gadsu/cleanup#58]
**Branch or release bug is on**
programming build tutorial level

**Describe the bug**
the kill screen 'restart' does not clear values

**To Reproduce**
1. go to level
2. die
3. click restart

**Expected behavior**
restart

**Additional context**
fixing now i just wanted a bug report

**Comment by rex8112** [comment]
Unable to reproduce on tutorialLevel and greenLevel, all values are getting reset appropriately.

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bugs 56, 58, 60 (1.5)](https://trello.com/c/G2Liw5Ny/376-fix-bugs-56-58-60-15)
