### ISSUE TITLE
Can walk into a space OBSOOO cannot touch you in

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#59]
**Branch or release bug is on**
be19c79

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
In the OBSOOO arena, The player can access a side of the wall that OBSOOO cannot go to. This allows the player to kill obsooo without him ever touching the player.

**To Reproduce**
Walk as far as you can to the side of the arena while fighting OBSOOO. He won't be able to hit you, but you can hit him in place.

**Expected behavior**
Expected OBSOOO to be able to hit the player or the player being unable to access that space.

**Screenshots**

[OBSOOO Break.zip](https://github.com/gadsu/cleanup/files/2861057/OBSOOO.Break.zip)

**Additional context**

**Comment by rex8112** [comment]
Fixed as of 679733dffd22cbdd37d9e37ff39b58a74602cd31
