### ISSUE TITLE
OBSOOO can get stuck

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#60]
**Branch or release bug is on**
985955d

**If found on Unity editor, what scene did you load**
Don't Destroy on load

**Describe the bug**
OBSOOO can get stuck in a corner of the arena and can't get out.

**To Reproduce**
Same way as getting OBSOOO out of the arena in the previous version. Hitting it during it's side jump will get him lodged into the corner of the arena.

**Expected behavior**
Expected the fight to carry on as normal

[OBSOOO STUCK.zip](https://github.com/gadsu/cleanup/files/2866470/OBSOOO.STUCK.zip)

**Comment by rex8112** [comment]
Could you do me a favor and see if while OBSOOO is stuck, if his onGround variable, or whichever it is called is true while he is there? Basically, just navigate to him without exiting Play Mode

**Comment by IanTrollinger** [comment]
Found another issue with OBSOOO getting stuck. This only works for the facingright = false. He will reach the side of the arena and continue jumping in place. I checked the information on OBSOOO and he is stuck in his commitment to doing his special side attack. 
[OBSOOO JUMP IN PLACE.zip](https://github.com/gadsu/cleanup/files/2870481/OBSOOO.JUMP.IN.PLACE.zip)

**Comment by IanTrollinger** [comment]
Also Riley, I retested the obsooo getting stuck in the corner. He is indeed listed as not being on the floor when he get's stuck in the corner.

**Comment by rex8112** [comment]
Sweet, I'll check it out next time I have the chance

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bugs 56, 58, 60 (1.5)](https://trello.com/c/G2Liw5Ny/376-fix-bugs-56-58-60-15)

**Comment by rex8112** [comment]
Fixed it, turns out the left patrol point was just a _little_ far to the left which caused him to get stuck on the wall or something like that, I think, maybe, I don't know...

**Comment by IanTrollinger** [comment]
OBSOOO for the new Green level gets stuck trying to preform the side charge.
