### ISSUE TITLE
Looping clean up animation

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#61]
**Branch or release bug is on**
Programming 985955d

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
The cleaning up animation will loop infinitely until another button is pressed to disrupt the animation.

**To Reproduce**
1. Press the E key but do not move or attack
2. Animation for cleanup will continue to loop.

**Expected behavior**
Expected the animation to end when 'E' key was let go of.

**Screenshots**

**Additional context**

**Comment by rachelgroth** [comment]
Partially fixed, now his fuckin sticker switches sides

**Comment by cjpetersen** [comment]
Having a run and mop animation will fix this a little bit but I will make it so he can't jump while moping.

**Comment by cjpetersen** [comment]
Fixed as of commit [df11124](https://github.com/gadsu/cleanup/commit/df111244c2ce57545e2458f2624ba6c7302fd4e3)
![image](https://user-images.githubusercontent.com/25103835/53278578-b2f45d00-36cf-11e9-8539-0b1563fea6b2.png)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish Implemented Player Animations (1)[1]](https://trello.com/c/rJ7JkbMP/381-polish-implemented-player-animations-11)
