### ISSUE TITLE
tile map has broken once again, really bad missing tiles

### ISSUE THREAD

**Issue by rachelgroth** [gadsu/cleanup#65]
**Branch or release bug is on**
Programming branch

**If found on Unity editor, what scene did you load**
tutorialLevel

**Describe the bug**
The tiles are real fucky, walking in invisible, pieces tiling in places they weren't placed

**To Reproduce**
1. Go to tutorial level
2. Look with ur eyeballs

**Expected behavior**
It not to be gross

**Screenshots**.
![image](https://user-images.githubusercontent.com/38136112/53102034-8a623c80-34f0-11e9-9da8-90b1a2fbeedc.png)

**Additional context**
Assuming it broke after Dillon touched it pls fix

**Comment by rex8112** [comment]
afaik this is fixed, it's just tiles on the level but not the actual map, because Unity.
