### ISSUE TITLE
Obsooo gets stuck in charge attack

### ISSUE THREAD

**Issue by Free-Shaman** [gadsu/cleanup#66]
**Branch or release bug is on**
Narrative branch, commit fb7851b

**If found on Unity editor, what scene did you load**
Tutorial2, and _DontDestroyOnLoad

**Describe the bug**
Obsooo gets stuck bouncing against one of the walls after it does the charge attack.

**To Reproduce**
1. Go to Obsooo fight
2. Hit Obsooo enough to trigger the charge attack
3. Dodge charge attack

**Additional context**
In the new tutorial level, Obsooo's arena is shorter than in the old level, this might have something to do with cause of the bug.

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add the Redesigned tutorial level into Unity (1) [1.5]](https://trello.com/c/nS1Pik39/352-add-the-redesigned-tutorial-level-into-unity-1-15)

**Comment by cjpetersen** [comment]
@rex8112 if you have a second I can't quite remember how you fixed this last time.

**Comment by IanTrollinger** [comment]
Once OBSOOO completes his charge without hitting the player, he gets stuck at the other end of the arena.

**Comment by cjpetersen** [comment]
@rex8112 is this still a problem any way you could fix it before Monday at 3:15? Or let me know what I would need to do to fix it.

**Comment by rex8112** [comment]
I think this is fixed?
