### ISSUE TITLE
Slime meter still doesn't reach 100%

### ISSUE THREAD

**Issue by Free-Shaman** [gadsu/cleanup#67]
**Branch or release bug is on**
Narrative, commit fb7851b

**If found on Unity editor, what scene did you load**
_DontDestroyOnLoad

**Describe the bug**
Can clear the entire stage of both slime enemies and innate slime and the progress bar still does not reach 100% clean

**To Reproduce**
1. Start playing the game
2. Clean everything
3. See error

**Comment by cjpetersen** [comment]
To me, it looks like the first slime you pick up doesn't move the meter, as such when you max out the amount your one short.
