### ISSUE TITLE
Crouch landing animation not working

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#68]
**Branch or release bug is on**
 dcd3584

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
Crouch animation has a delayed activation/ does not activate. So the player is stuck in their falling animation though can still move, attack, and jump.

**To Reproduce**
Jump on any level.

**Expected behavior**
Expected the crouch animation to play.

**Screenshots**
[Crouch animation delay or not working.zip](https://github.com/gadsu/cleanup/files/2894416/Crouch.animation.delay.or.not.working.zip)

**Additional context**

**Comment by IanTrollinger** [comment]
[Crouch in air.zip](https://github.com/gadsu/cleanup/files/2895649/Crouch.in.air.zip)
Player may crouch in air during a long decent and reset to a standing pose. Not sure what might be causing this. If you Programmers have anything you want me to check with this just say.

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Crouching after a big jump (1)[1]](https://trello.com/c/P7gy0p7h/379-implement-crouching-after-a-big-jump-11)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Crouching after a big jump (1)[1]](https://trello.com/c/P7gy0p7h/379-implement-crouching-after-a-big-jump-11)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Crouching after a big jump (1)[1]](https://trello.com/c/P7gy0p7h/379-implement-crouching-after-a-big-jump-11)

**Comment by cjpetersen** [comment]
Fixed as of commit [df11124](https://github.com/gadsu/cleanup/commit/df111244c2ce57545e2458f2624ba6c7302fd4e3)
![image](https://user-images.githubusercontent.com/25103835/53278578-b2f45d00-36cf-11e9-8539-0b1563fea6b2.png)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish Implemented Player Animations (1)[1]](https://trello.com/c/rJ7JkbMP/381-polish-implemented-player-animations-11)
