### ISSUE TITLE
Barney Does not pause on Pause

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#70]
**Branch or release bug is on**
Programming  a4dbd99

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
Pausing the game does not pause barney, the animations pause but the slime slinging code continues and when the game is unpaused the tentacles can fly around and get stuck in the ceiling.

**To Reproduce**
1. Pause game when facing Barney (anywhere on Green level works too, just delayed sighting of slime)
2. See bug.

**Expected behavior**
Expected all code for Barney to pause.

[Barney Pause issue.zip](https://github.com/gadsu/cleanup/files/2907191/Barney.Pause.issue.zip)

**Comment by rex8112** [comment]
I'll look at it and keep it in mind but I probably won't fix it until I finish Barney

**Comment by cjpetersen** [comment]
@rex8112 is this still an issue.

**Comment by ladyflyers29** [comment]
This is fixed now with @rex8112
