### ISSUE TITLE
Barney can be knocked out of place

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#71]
**Branch or release bug is on**
Programming ec0c957

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
If the player can run into Barney by moving along his tentacles, Barney can be moved out of place and can move about the screen

**To Reproduce**
1. Jump on tentacles (Right side is easiest)
2. Move towards Barney on the tentacles
3. If contact is made with Barney's body, and contact is kept during knockback Barney will be moved. (Possibly because of knockback)

**Expected behavior**
Expected Barney to remain in place

**Screenshots**
[Barney Knockback.zip](https://github.com/gadsu/cleanup/files/2910883/Barney.Knockback.zip)

**Additional context**
It might be the knock back that affects the player affecting barney.

**Comment by rex8112** [comment]
Barney is still pretty WIP and I haven't messed with his ability to move or not move, which is probably something I won't overly touch on until I implement stage 3

**Comment by rex8112** [comment]
Please retest after improvement, thank you

**Comment by IanTrollinger** [comment]
[Barnycan be moved.zip](https://github.com/gadsu/cleanup/files/3044837/Barnycan.be.moved.zip)
Barney can still be knocked out of place. While I think re enabling the damage to the player might help (as I tested this with god mode) the player can knock Barney out of his correct landing place with his fall and render him harmless.

**Comment by rex8112** [comment]
If you start off of Don'tDestroyOnLoad, this won't be an issue since Barney's body will damage you and therefore apply knockback. For now, will consider this fixed. If you can break it with knockback enabled, then we can reopen.
