### ISSUE TITLE
Can keep screen from zooming back out on idle

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#72]
**Branch or release bug is on**
Programming ec0c957

**If found on Unity editor, what scene did you load**
Don't Destroy on load

**Describe the bug**
When the screen zooms in on the player on idle, the player can prevent the screen from zooming back out by holding down a button.

**To Reproduce**
1. Wait for screen to zoom in.
2. Hold down the clean button.
3. Feel free to move around, as long as you hold down the clean button, the screen will not zoom back out.

**Expected behavior**
Expected the screen to zoom back out on input.

**Screenshots**

**Additional context**

**Comment by ladyflyers29** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0.25) fix bug #72 (Can keep screen from zooming back out on idle) [0.25]](https://trello.com/c/uS8R13RZ/425-025-fix-bug-72-can-keep-screen-from-zooming-back-out-on-idle-025)
