### ISSUE TITLE
Pit does kill player

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#73]
**Branch or release bug is on**
Programming 004cfda

**If found on Unity editor, what scene did you load**
Don't destroy on load

**Describe the bug**
Pit in Green level does not kill or teleport the player

**To Reproduce**
1. Jump in pit in the green slime jump section
2. See bug

**Expected behavior**
Expected to be teleported back to the beginning.
<img width="536" alt="kingdom error" src="https://user-images.githubusercontent.com/27169126/53591634-152ee100-3b5a-11e9-8fd3-00a0d3d19a5e.PNG">

**Comment by cjpetersen** [comment]
You can jump out if you have enough green slime. Should put a few more enemy' down there.

**Comment by cjpetersen** [comment]
@Free-Shaman I'm going to close this but remember to add a way to get out more easily.
