### ISSUE TITLE
Player delays upon hitting the ground before actually landing

### ISSUE THREAD

**Issue by rachelgroth** [gadsu/cleanup#78]
**Branch or release bug is on**
programming absentmonkey

**Describe the bug**
it jump and it land

**To Reproduce**
1. jump
2. land
3. see bad animation

**Comment by cjpetersen** [comment]
Fixed as of commit f6a043a by changing the transition from the inAir to Crouch animation. 
How the animations feel will be a question during the all fools day playtests if playtesters identify any animation problems it can be revisited.
