### ISSUE TITLE
Player loses slime collected

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#79]
**Branch or release bug is on**
 42f6cd9

**If found on Unity editor, what scene did you load**
Don't destroy on load, in greenlevel

**Describe the bug**
The player can loose all slime collected by attempting to clean a climbable wall. Either by running into it or running off a cliff into one while holding down E will drain your slime reserves.

**To Reproduce**
1. Collect slime.
2: Find climbable slime wall (If it starts at the ground that's ideal)
3: Hold down "Clean" button and walk into the slime wall.
4: See bug.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ladyflyers29** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug #79 (player can loose all slime collected) (2)](https://trello.com/c/VL2mLCIL/424-fix-bug-79-player-can-loose-all-slime-collected-2)

**Comment by ladyflyers29** [comment]
took off the old player controller from the player and it fixed this. Ian can't break this anymore. :)
