### ISSUE TITLE
Running mop will not disappear when movement stops

### ISSUE THREAD

**Issue by IanTrollinger** [gadsu/cleanup#84]
**Branch or release bug is on**
f6a043a

**If found on Unity editor, what scene did you load**
Don't Destroy on load

**Describe the bug**
When the player stops movement while cleaning the item for the running mop stays visible while the player character starts the still cleaning animation with the correct mop for it.

**To Reproduce**
1. Hold down cleaning button.
2. Move around
3. Stop movement while holding down cleaning button.
4. See bug

**Expected behavior**
Expected running mop to disappear when movement ceased.

**Screenshots**
[Runningmopissue.zip](https://github.com/gadsu/cleanup/files/3019583/Runningmopissue.zip)

**Additional context**

**Comment by ladyflyers29** [comment]
--Fixed by carl--

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General Polish see checklist (1.5)[1.5]](https://trello.com/c/ms4GauYy/426-general-polish-see-checklist-1515)
