### ISSUE TITLE
Mime Cleaning

### ISSUE THREAD

**Issue by shadowweaver95** [gadsu/cleanup#85]
**Branch or release bug is on**
The One

**If found on Unity editor, what scene did you load**
 `_DontDestroyOnLoad`

**Describe the bug**
The mop can disappear and the player runs in place as though they are trying to clean.

**To Reproduce**
1. Go to 'dontdestroyonload'
2. Click on 'play'
3. attempt to run for a short distance while cleaning and stop abruptly

**Expected behavior**
player is expected to go into the idle animation

**Screenshots**

**Additional context**

**Comment by cjpetersen** [comment]
Fixed as of commit f6a043a

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General Polish see checklist (1.5)[1.5]](https://trello.com/c/ms4GauYy/426-general-polish-see-checklist-1515)
