### ISSUE TITLE
Walls can't stop me

### ISSUE THREAD

**Issue by shadowweaver95** [gadsu/cleanup#86]
**Branch or release bug is on**
The One

**If found on Unity editor, what scene did you load**
`_DontDestroyOnLoad`

**Describe the bug**
player can attack and walk through the right obsooo wall

**To Reproduce**
1. Go to 'dont destroy on load'
2. Click on 'play'
3. Walk to the obsooo location
4. Attempt to walk through and attack and move through the right wall

**Expected behavior**
The wall should stop the player completely 

**Screenshots**

**Additional context**

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General Polish see checklist (1.5)[1.5]](https://trello.com/c/ms4GauYy/426-general-polish-see-checklist-1515)
