### ISSUE TITLE
Double jumping feels weird 

### ISSUE THREAD

**Issue by cjpetersen** [gadsu/cleanup#87]
**Branch or release Issue is on**
The One, 

**If found on Unity editor, what scene did you load**
_DontDestroyOnLoad

**Describe the Issue**
When you double jump it can sometimes not do what you expect like sticking a little longer than average depending on how much of the wall collider you are stuck to. 

**To Reproduce**
1. Jump on a double jump wall and jump off

**Expected behavior**
The player should fly into the air and have pretty concise control over where they land.

**Screenshots**

**Additional context**

**Comment by rex8112** [comment]
Please test again

**Comment by cjpetersen** [comment]
After the fix to animations not sure what else to do.
